# ==========================================
# 網站基本設定 (Site Settings)
# ==========================================
title: "Punch與他的社會工程學"                    # 網站大標題
subtitle: "Punch是隻貓 " # 副標題
description: "他真的是隻貓" # 網站簡介

# 個人資訊
author:
  name: "Yong"
  bio: "人生目標是一天工作兩小時"
  
# 網址設定 
url: "https://mic219219.github.io/Punch---His-Social-Engineering/"
baseurl: ""

# 外觀設定 (預設深色模式)
theme: minima
minima:
  skin: dark
